# part 1


How to create an empty and a full NumPy array?

Create a Numpy array filled with all zeros

Create a Numpy array filled with all ones

Flatten a 2d numpy array into 1d array

Reverse a numpy array

Change data type of given numpy array

In [1]:
# How to create an empty and a full NumPy array?
import numpy as np

empty_array_2d = np.empty((3, 4))
print(empty_array_2d)


[[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306]
 [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]
 [8.45596650e-307 9.34602321e-307 4.94065646e-322 0.00000000e+000]]


In [7]:
# Create a Numpy array filled with all zeros
a=np.zeros(6)
a
np.zeros((3,2)) #2D array

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
# Create a Numpy array filled with all ones
a=np.ones((4,5),dtype=int)
a

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [28]:
# Flatten a 2d numpy array into 1d array
a=np.array((1,2,3,4,5,6,7,8))
b=a.reshape((4,2))
print(b)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [29]:
c=a.flatten() #to flatten array into 1d 
print(c)

[1 2 3 4 5 6 7 8]


In [38]:
# Reverse a numpy array
arr=np.arange(1,9)
print(arr)
reverse_arr=arr[::-1]
print("Reverse a numpy array is ",reverse_arr)

[1 2 3 4 5 6 7 8]
Reverse a numpy array is  [8 7 6 5 4 3 2 1]


In [44]:
# Change data type of given numpy array
arr = np.array([10, 20, 30, 40, 50]) 
# Print the array 
print(arr)

# Print the dtype 
print(arr.dtype)

# change the dtype to 'float64' 
arr = arr.astype('float64') 
print(arr) 
  
# print the data type 
print(arr.dtype)

[10 20 30 40 50]
int32
[10. 20. 30. 40. 50.]
float64


# part 2

Get the maximum value from given matrix

Get the minimum value from given matrix

Find the number of rows and columns of a given matrix using NumPy

Select the elements from a given matrix

Find the sum of values in a matrix

Calculate the sum of the diagonal elements of a NumPy array

Adding and Subtracting Matrices in Python

Ways to add row/columns in numpy array

In [59]:
# Get the maximum value from given matrix
arr=np.arange(10)
print(arr)
print("maximum value from given matrix is:",arr.max())

[0 1 2 3 4 5 6 7 8 9]
maximum value from given matrix is: 9


In [60]:
#Get the minimum value from given matrix
print("minimum value from given matrix is:",arr.min())

minimum value from given matrix is: 0


In [77]:
# Find the number of rows and columns of a given matrix using NumPy
arr=np.arange(14)
b=arr.reshape(7,2)
b

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13]])

In [79]:
dimension=b.shape
rows, columns = dimension
print("Rows",rows)
print("Columns:",columns)


Rows 7
Columns: 2


In [83]:
# Select the elements from a given matrix

arr=np.arange(25).reshape(5,5)
print(arr)
print("To find element from given matrix:",arr[1][3])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
To find element 8 from given matrix: 8


In [89]:
# Find the sum of values in a matrix
arr_=np.arange(16).reshape(4,4)
print(arr_)
print("sum of values in a matrix :",arr_.sum())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
sum of values in a matrix : 120


In [90]:
# Calculate the sum of the diagonal elements of a NumPy array
arr_=np.arange(16).reshape(4,4)
print(arr_)
sum_diag = np.trace(arr_)
print("sum of the diagonal elements of a NumPy array:",sum_diag)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
sum of the diagonal elements of a NumPy array: 30


In [94]:
# Adding and Subtracting Matrices in Python
a = np.array([10,20,30,40])
b = np.array ([5,10,15,20])
add=a+b
sub=a-b
print("Adding matrices value",add)
print("Subtracting matrices value",sub)

Adding matrices value [15 30 45 60]
Subtracting matrices value [ 5 10 15 20]


In [98]:
# Ways to add row/columns in numpy array
arr_=np.arange(16).reshape(4,4)
print(arr_)
a=arr_.sum(axis=1) #for adding of row axis=1
print("Adding of rows :",a)
b=arr_.sum(axis=0) #for adding of row axis=0
print("Adding of columns :",b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Adding of rows : [ 6 22 38 54]
Adding of columns : [24 28 32 36]
